[project]
name = "arkmod"
version = "0.0.1"
description = "Ark modding tools"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
]

[project.scripts]
arkmod = "arkmod.__main__:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
